apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "k8-web-chart.fullname" . }}
  labels:
    app: {{ template "k8-web-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "k8-web-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "k8-web-chart.name" . }}
    spec:
      volumes:
      - name: web-content
        configMap:
          name: {{ template "k8-web-chart.fullname" . }}-config
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: web-content
          mountPath: /app/index.php
          subPath: index.php
        resources:
          {{- toYaml .Values.resources | nindent 12 }}