apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "k8-web-chart.fullname" . }}
  labels:
    app: {{ template "k8-web-chart.name" . }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ template "k8-web-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "k8-web-chart.name" . }}
    spec:
      volumes:
      - name: web-content
        configMap:
          name: config--{{ template "k8-web-chart.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: webdevops/php-nginx:8.3-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: web-content
          mountPath: /app/index.php
          subPath: index.php
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi