apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8-web-chart.fullname" . }}
  labels:
    app: {{ template "k8-web-chart.name" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
      protocol: TCP
  selector:
    app: {{ template "k8-web-chart.name" . }}
