apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8-web-chart.fullname" . }}
  annotations:
    # Annotations for external HAProxy integration
    external-dns.alpha.kubernetes.io/hostname: haproxy.hpelab.local
    # Optional: Use service.beta.kubernetes.io/external-traffic annotation if needed
    service.beta.kubernetes.io/external-traffic: "Local"
  labels:
    app: {{ template "k8-web-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ template "k8-web-chart.name" . }}