apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8-web-chart.fullname" . }}
  labels:
    app: {{ template "k8-web-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ template "k8-web-chart.name" . }}