apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:alpine
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - sh
        - -c
        - |
          echo "<html>
            <head>
              <title>Welcome to Kubernetes Info Dashboard</title>
              <style>
                body {
                  font-family: 'Segoe UI', Arial, sans-serif;
                  text-align: center;
                  padding: 50px;
                  background: linear-gradient(45deg, #6a11cb 0%, #2575fc 100%);
                  color: #333;
                  margin: 0;
                  min-height: 100vh;
                }
                h1 {
                  color: white;
                  text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
                  margin-bottom: 40px;
                  font-size: 2.5em;
                }
                .info {
                  background: rgba(255, 255, 255, 0.95);
                  border-radius: 15px;
                  box-shadow: 0 8px 32px rgba(0,0,0,0.1);
                  padding: 30px 50px;
                  display: inline-block;
                  text-align: left;
                  margin-top: 20px;
                  transition: transform 0.3s ease;
                }
                .info:hover {
                  transform: translateY(-5px);
                }
                .info p {
                  margin: 20px 0;
                  font-size: 18px;
                  line-height: 1.6;
                }
                .info strong {
                  color: #2575fc;
                  font-size: 20px;
                }
              </style>
            </head>
            <body>
              <h1>Kubernetes Pod Dashboard</h1>
              <div class='info'>
                <p><strong> Node Name:</strong> $NODE_NAME</p>
                <p><strong> Pod Name:</strong> $POD_NAME</p>
                <p><strong> Node IP:</strong> $HOST_IP</p>
                <p><strong> Namespace:</strong> $NAMESPACE</p>
              </div>
            </body>
            </html>" > /usr/share/nginx/html/index.html &&
                nginx -g 'daemon off;'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
