apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  index.html: |
            <html>
            <head>
              <title>Node Info</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  text-align: center;
                  padding: 50px;
                  background-color: #f4f4f9;
                  color: #333;
                }
                h1 {
                  color: #4CAF50;
                }
                .info {
                  margin-top: 20px;
                  padding: 10px;
                  border: 1px solid #ddd;
                  display: inline-block;
                  text-align: left;
                }
              </style>
            </head>
            <body>
              <h1>Welcome to Kubernetes Web Server</h1>
              <div class='info'>
                <p><strong>Node Name:</strong> ${NODE_NAME}</p>
                <p><strong>Pod Name:</strong> ${POD_NAME}</p>
                <p><strong>Node IP:</strong> ${HOST_IP}</p>
                <p><strong>Namespace:</strong> ${NAMESPACE}</p>
              </div>
            </body>
            </html>     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:alpine
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081



