apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: {{ template "voting-app.fullname" . }}-postgres
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        name: {{ template "voting-app.fullname" . }}-postgres
        env:
        - name: POSTGRES_USER
          value: {{ .Values.database.credentials.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.credentials.password }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ template "voting-app.fullname" . }}-database-pvc
