apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.database.name }}
  name: {{ .Values.database.name }}
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
      - image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        name: postgres
        env:
        - name: POSTGRES_USER
          value: {{ .Values.database.credentials.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.credentials.password }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Values.database.storage.claimname }}
