apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: postgres-service
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - name: postgres
    port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
  selector:
    app: db