apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: {{ template "voting-app.fullname" . }}-postgres-service
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - name: {{ template "voting-app.fullname" . }}-postgres-service
    port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
  selector:
    app: db