apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: {{ template "voting-app.fullname" . }}-redis-service
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    app: redis
