apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.storage.claimname }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
  storageClassName: {{ .Values.redis.storage.classname }}
