apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result-service
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: result
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    nodePort: {{ .Values.result.service.nodePort }}
  selector:
    app: result