apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: {{ template "voting-app.fullname" . }}-result
spec:
  replicas: {{ .Values.result.replicas }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: {{ .Values.result.image.repository }}
        name: {{ .Values.result.name }}
        ports:
        - containerPort: 80
          name: result
