apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: {{ .Values.result.service.name }}
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    nodePort: {{ .Values.result.service.nodePort }}
    nodePort: 31001
  selector:
    app: result
