apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - name: {{ template "voting-app.fullname" . }}-result-service
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    nodePort: {{ .Values.result.service.nodePort }}
  selector:
    app: result