apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: {{ template "voting-app.fullname" . }}-vote-service
spec:
  type: {{ .Values.vote.service.type }}
  ports:
  - name: {{ template "voting-app.fullname" . }}-vote-service
    port: {{ .Values.vote.service.port }}
    targetPort: {{ .Values.vote.service.targetPort }}
    nodePort: {{ .Values.vote.service.nodePort }}
  selector:
    app: vote