apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: {{ template "voting-app.fullname" . }}-vote
spec:
  replicas: {{ .Values.vote.replicas }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: {{ .Values.vote.image.repository }}
        name: vote
        ports:
        - containerPort: 80
          name: vote
