apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: {{ .Values.vote.name }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
  - name: {{ .Values.vote.service.name }}
    port: {{ .Values.vote.service.port }}
    targetPort: {{ .Values.vote.service.targetPort }}
    nodePort: {{ .Values.vote.service.nodePort }}
  selector:
    app: vote