apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: {{ template "voting-app.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.worker.image.repository }}
        name: worker