apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: {{ .Values.worker.name }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.worker.image.repository }}
        name: worker
